[package]
name = "todo"
version = "0.1.0"
authors = ["Piece123 <taka.rock.i4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.1.0"
thiserror = "1.0.22"
